### ISSUE TITLE
Error during build of Vite 5 and Svelte

### ISSUE THREAD

**Issue by JoshuaHintze** [shixuanhong/vite-plugin-css-export#4]
I've been a regular user of this module for react projects. I'm switching to Svelte and Vite 5. During normal run it works great, however doing a vite build I get the following error message

```
✓ 112 modules transformed.
[vite:css-post] Failed to convert JavaScript value `Object {"code":"","map":{"mappings":""},"moduleSideEffects":"no-treeshake"}` into rust type `String`
file: /home/joshh/redsky/redsky/redsky-quickstart-svelte/src/themes/colors.scss?export
transforming (113) src/app.scsserror during build:
Error: Failed to convert JavaScript value `Object {"code":"","map":{"mappings":""},"moduleSideEffects":"no-treeshake"}` into rust type `String`
    at Object.parseAst [as parse] (file:///home/joshh/redsky/redsky/redsky-quickstart-svelte/node_modules/rollup/dist/es/shared/parseAst.js:2142:23)
    at Object.vitePostCodeHandler (file:///home/joshh/redsky/redsky/redsky-quickstart-svelte/node_modules/vite-plugin-css-export/dist/index.mjs:121:20)
    at cssPostPlugin.transform (file:///home/joshh/redsky/redsky/redsky-quickstart-svelte/node_modules/vite-plugin-css-export/dist/index.mjs:155:38)
error Command failed with exit code 1.
```

Any suggestions?

**Comment by JoshuaHintze** [comment]
Actually this seems to be more so related to not supporting Vite 5. Any chance of updating to support vite 5?

**Comment by JoshuaHintze** [comment]
@shixuanhong

**Comment by shixuanhong** [comment]
> Actually this seems to be more so related to not supporting Vite 5. Any chance of updating to support vite 5?

Ok, I will support Vite 5 this week.

**Comment by JoshuaHintze** [comment]
Thank you. I’m looking forward to it. I’ll give you feedback as soon as you have a version for me to try.

**Comment by shixuanhong** [comment]
> Thank you. I’m looking forward to it. I’ll give you feedback as soon as you have a version for me to try.

@GimpMaster You can try [v3.0.0-beta.0](https://www.npmjs.com/package/vite-plugin-css-export/v/3.0.0-beta.0).

**Comment by JoshuaHintze** [comment]
Unfortunately I still get the same error

```
[vite:css-post] Failed to convert JavaScript value `Object {"code":"","map":{"mappings":""},"moduleSideEffects":"no-treeshake"}` into rust type `String`
file: /home/joshh/redsky/redsky/redsky-quickstart-svelte/src/themes/colors.scss?export
transforming (119) src/lib/framework/inputText/InputText.scsserror during build:
Error: Failed to convert JavaScript value `Object {"code":"","map":{"mappings":""},"moduleSideEffects":"no-treeshake"}` into rust type `String`
    at Object.parseAst [as parse] (file:///home/joshh/redsky/redsky/redsky-quickstart-svelte/node_modules/rollup/dist/es/shared/parseAst.js:2142:23)
    at Object.vitePostCodeHandler (file:///home/joshh/redsky/redsky/redsky-quickstart-svelte/node_modules/vite-plugin-css-export/dist/index.mjs:125:20)
    at cssPostPlugin.transform (file:///home/joshh/redsky/redsky/redsky-quickstart-svelte/node_modules/vite-plugin-css-export/dist/index.mjs:157:38)
error Command failed with exit code 1.
```

Here is my dependencies from package.json

```
	"devDependencies": {
		"@sveltejs/adapter-auto": "^3.0.0",
		"@sveltejs/kit": "^2.0.0",
		"@sveltejs/vite-plugin-svelte": "^3.0.0",
		"@types/jsonwebtoken": "^9.0.5",
		"@types/lodash.clonedeep": "^4.5.9",
		"prettier": "^3.1.1",
		"prettier-plugin-svelte": "^3.1.2",
		"sass": "^1.69.5",
		"svelte": "^4.2.7",
		"svelte-check": "^3.6.2",
		"svelte-language-server": "^0.16.3",
		"tslib": "^2.4.1",
		"typescript": "^5.0.0",
		"typescript-svelte-plugin": "^0.3.37",
		"vite": "^5.0.3",
		"vite-plugin-css-export": "3.0.0-beta.0"
	},
	"type": "module",
	"dependencies": {
		"@capacitor/core": "^5.6.0",
		"@capacitor/haptics": "^5.0.6",
		"axios": "^1.6.2",
		"classnames": "^2.3.2",
		"jsonwebtoken": "^9.0.2",
		"lodash.clonedeep": "^4.5.0",
		"svelte-sonner": "^0.3.11",
		"sveltekit-superforms": "^1.13.1",
		"zod": "^3.22.4"
	}
```

**Comment by JoshuaHintze** [comment]
Here is an example of how I'm using it.

```
<script lang="ts">
	import colors from '$themes/colors.scss?export';
	import './PageBar.scss';
	import { Box, Text } from '$lib/framework';

	export let title: string = 'Page Title';
</script>

<Box elementType="header" class="rsPageBar">
	<Text variant="h2" weight="semiBold" color={colors.primaryBlue900}>{title}</Text>
	<slot />
</Box>
```

Like I said it works just fine in `yarn dev` but when I go to `yarn build` I get the error above.  I did notice in your examples you had &inline. I tried that as well but didn't make a difference.

**Comment by JoshuaHintze** [comment]
Also if it helps here is my colors.scss and I am using SvelteKit (noticed your example was just Svelte)

```
// Generated File Do not edit!
:root {
	--nofill: #ffffff;
	--primaryTextColor: #212529;
	--neutralBlack: #000000;
	--neutralGrey900: #212529;
	--neutralGrey800: #343a40;
	--neutralGrey700: #495057;
	--neutralGrey600: #868e96;
	--neutralGrey500: #adb5bd;
	--neutralGrey400: #ced4da;
	--neutralGrey300: #dee2e6;
	--neutralGrey200: #e9ecef;
	--neutralGrey100: #f1f3f5;
	--neutralGrey50: #f8f9fa;
	--neutralWhite: #ffffff;
	--primaryBlue900: #0d3659;
	--primaryBlue700: #1d588b;
	--primaryBlue500: #0088ff;
	--primaryBlue300: #66b8ff;
	--primaryBlue100: #c8e2f9;
	--primaryBlue50: #f6fafe;
	--primaryBlue5008percent: #0088ff;
	--accentSuccessLight: #d3fccf;
	--accentSuccess: #20a612;
	--accentSuccessDark: #0a4a03;
	--accentErrorLight: #feedec;
	--accentError: #e51a3c;
	--accentErrorDark: #750800;
	--accentWarningLight: #fff5cc;
	--accentWarning: #e6900f;
	--accentWarningDark: #5c4900;
	--accentInfoLight: #cce6ff;
	--accentInfo: #1469b8;
	--accentInfoDark: #002f5c;
	--accentSkeleton: #d2d4d6;
};

// Exports are for use in Javascript
:export {
	nofill: var(--nofill);
	primaryTextColor: var(--primaryTextColor);
	neutralBlack: var(--neutralBlack);
	neutralGrey900: var(--neutralGrey900);
	neutralGrey800: var(--neutralGrey800);
	neutralGrey700: var(--neutralGrey700);
	neutralGrey600: var(--neutralGrey600);
	neutralGrey500: var(--neutralGrey500);
	neutralGrey400: var(--neutralGrey400);
	neutralGrey300: var(--neutralGrey300);
	neutralGrey200: var(--neutralGrey200);
	neutralGrey100: var(--neutralGrey100);
	neutralGrey50: var(--neutralGrey50);
	neutralWhite: var(--neutralWhite);
	primaryBlue900: var(--primaryBlue900);
	primaryBlue700: var(--primaryBlue700);
	primaryBlue500: var(--primaryBlue500);
	primaryBlue300: var(--primaryBlue300);
	primaryBlue100: var(--primaryBlue100);
	primaryBlue50: var(--primaryBlue50);
	primaryBlue5008percent: var(--primaryBlue5008percent);
	accentSuccessLight: var(--accentSuccessLight);
	accentSuccess: var(--accentSuccess);
	accentSuccessDark: var(--accentSuccessDark);
	accentErrorLight: var(--accentErrorLight);
	accentError: var(--accentError);
	accentErrorDark: var(--accentErrorDark);
	accentWarningLight: var(--accentWarningLight);
	accentWarning: var(--accentWarning);
	accentWarningDark: var(--accentWarningDark);
	accentInfoLight: var(--accentInfoLight);
	accentInfo: var(--accentInfo);
	accentInfoDark: var(--accentInfoDark);
	accentSkeleton: var(--accentSkeleton);
}
```

**Comment by shixuanhong** [comment]
@GimpMaster I have found the problem, thank you for your information.

**Comment by JoshuaHintze** [comment]
@shixuanhong - Great. Looking forward to it.

**Comment by shixuanhong** [comment]
@GimpMaster I believe it will work fine in vite5, please try using `v3.0.0-beta.1`.

**Comment by JoshuaHintze** [comment]
Hello @shixuanhong  - I think we are almost there. It built just great, no issues there. However I'm using sveltekit and I import this into a component like you suggest with the &export on the end.

After its done building I ran yarn preview (since sveltekit runs their backend SSR in nodejs). I'm now getting this error when I try to load the page.

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/joshh/redsky/redsky/redsky-quickstart-svelte/.svelte-kit/output/server/chunks/colors.js' imported from /home/joshh/redsky/redsky/redsky-quickstart-svelte/.svelte-kit/output/server/chunks/PageContainer.js
    at new NodeError (node:internal/errors:405:5)
    at finalizeResolution (node:internal/modules/esm/resolve:327:11)
    at moduleResolve (node:internal/modules/esm/resolve:980:10)
    at defaultResolve (node:internal/modules/esm/resolve:1193:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:403:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:372:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:249:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:39)
    at link (node:internal/modules/esm/module_job:75:36) {
  url: 'file:///home/joshh/redsky/redsky/redsky-quickstart-svelte/.svelte-kit/output/server/chunks/colors.js',
  code: 'ERR_MODULE_NOT_FOUND'
}

So it seems to be looking for the colors.js that I tried importing.

![image](https://github.com/shixuanhong/vite-plugin-css-export/assets/7818200/aceb634e-1488-47c3-a7f2-bc4052b7caea)


In this image it looks like it got built to colors.css but sveltekit is expecting it as js for some reason?

**Comment by shixuanhong** [comment]
@GimpMaster Replace all `?export` with `?export&inline`, and then import `colors.scss` in the entry file, like
```js
import './colors.scss'
```
This is a temporary solution, if you are more urgent, you can do this first.

**Comment by shixuanhong** [comment]
> @GimpMaster Replace all `?export` with `?export&inline`, and then import `colors.scss` in the entry file, like
> 
> ```js
> import './colors.scss'
> ```
> 
> This is a temporary solution, if you are more urgent, you can do this first.

In fact, in your case, you only need to use CSS Modules and do not need this plugin.

**Comment by JoshuaHintze** [comment]
Hmm, I'm not familiar with using css modules in sveltekit. Does it allow you to import into typescript the values that are exported (i.e. color hex codes?)

**Comment by JoshuaHintze** [comment]
@shixuanhong - Looks like the &inline does work.
